conda-forge/catboost-feedstock

recipe/bld.bat
recipe/build.sh
recipe/meta.yaml

Checklist
* [Х] Used a fork of the feedstock to propose changes
* [Х] Reset the build number to `0` (if the version changed)
* [Х] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [Х] Ensured the license file is being packaged.

Version updated and python 3.7 support added

---

recipe/meta.yaml

Upgrade catboost to v0.10.0

---

recipe/meta.yaml

update to 0.10.2

---

.appveyor.yml
.ci_support/linux_python3.7.yaml
.ci_support/osx_python3.7.yaml
.ci_support/win_python3.7.yaml
.circleci/config.yml
.travis.yml
recipe/bld.bat
recipe/build.sh
recipe/meta.yaml

add python 3.7 to conda-forge

---

recipe/meta.yaml

CatBoost 0.12.1.1

---

recipe/meta.yaml

CatBoost 0.12.2 (please travis-ci)

---

.appveyor.yml
.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
recipe/meta.yaml

CatBoost v0.13

---

recipe/meta.yaml

CatBoost 0.13.1

---

recipe/meta.yaml

CatBoost v0.14.1

---

README.md
recipe/meta.yaml

catboost.ai

---

.github/CODEOWNERS
README.md
recipe/meta.yaml

add andrey-khropov as package maintainer

---

recipe/meta.yaml

0.23 rebuild

---

recipe/meta.yaml

Release 0.24

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
.ci_support/linux_64_python3.7.____cpythonpython_implcpython.yaml
.ci_support/linux_64_python3.8.____cpythonpython_implcpython.yaml
.ci_support/linux_64_python3.9.____cpythonpython_implcpython.yaml
.ci_support/migrations/python39.yaml
.ci_support/osx_64_python3.9.____cpythonpython_implcpython.yaml
.ci_support/win_64_python3.9.____cpython.yaml
.scripts/build_steps.sh
.scripts/logging_utils.sh
.scripts/run_docker_build.sh
.scripts/run_osx_build.sh
LICENSE.txt
README.md
recipe/LICENSE
recipe/bld.bat
recipe/build.sh
recipe/meta.yaml

Since I cannot push to https://github.com/conda-forge/catboost-feedstock/pull/67 I opened the separate pull request. 
Closes https://github.com/conda-forge/catboost-feedstock/pull/67

Rebuild python39 

---

recipe/meta.yaml

release 0.26

---

recipe/meta.yaml

Checklist
* [] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)

Release 1.0.3

---

recipe/meta.yaml

Release 1.0.4

---

recipe/meta.yaml

Checklist
Python-graphviz fixes the pip check issue with graphviz. I just tried on Windows and Linux. The test phase was successfull.

Fixing graphviz issue

---

recipe/build.sh
recipe/meta.yaml

continue release 1.0.5

---

recipe/meta.yaml

release v1.0.6

---

recipe/meta.yaml

release 1.1

---

recipe/meta.yaml

Checklist
Rebuild and rererendering are not needed, this change is just cleanup that does not affect recipe results

Remove obsolete Python 2.7 dependency

---

recipe/meta.yaml

Release 1.2.1

---

recipe/meta.yaml

release 1.2.2

---

recipe/bld.bat
recipe/build.sh
recipe/meta.yaml

Add python 3.12 wheels to build scripts

---

recipe/meta.yaml

Release 1.2.7

---

recipe/meta.yaml

Fixes https://github.com/conda-forge/catboost-feedstock/issues/122
Checklist
I did not bump the build number to not re-release too often, the next update is expected soon with the merge of PR #120

Fix doc_url

---

recipe/meta.yaml

Remove obsolete 'skip' specifications. Fix #136
